version: '2'
services:
  db:
    image: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=wp
      - MYSQL_USER=wp
      - MYSQL_PASSWORD=wp
  wp:
    build: .
    volumes:
      - ./local-config.php:/var/www/html/wp-config.php
      - /var/www/html/wp-content
      - ./fora:/var/www/html/wp-content/themes/fora
      - ./loffle:/var/www/html/wp-content/themes/loffle
    ports:
      - "8080:80"
    links:
      - db
